#!/usr/bin/env python3

import os, sys

def pcoord(s):
    integral = s[:2 + (len(s) % 2)]
    s = s[len(integral):]
    rc = float(integral)
    d = 1
    while len(s):
        d *= 60
        rc += float(s[:2]) / d
        s = s[2:]
    return rc

def pcoords(s):
    latsign, s = s[0], s[1:]
    p = s.index('+' if '+' in s else '-')
    lat, lonsign, lon = s[:p], s[p], s[p + 1:]
    lat = pcoord(lat) * (+1 if latsign == '+' else -1)
    lon = pcoord(lon) * (+1 if lonsign == '+' else -1)
    return (lat, lon)

try:
    with open("/usr/share/zoneinfo/zone1970.tab", 'rb') as file:
        tab = file.read().decode('utf-8', 'strict').split('\n')
    
    tz = os.readlink('/etc/localtime')
    if '/zoneinfo/' in tz:
        tz = tz[tz.find('/zoneinfo/') + len('/zoneinfo/'):]
    
    for line in tab:
        if line.startswith('#'):
            continue
        fields = line.split('\t')
        if len(fields) < 3:
            continue
        if fields[2] == tz:
            (lat, lon) = pcoords(fields[1])
            print('%f %f' % (lat, lon))
            sys.exit(0)
except:
    pass
sys.exit(1)
